version: '3'
services:
  app:
    build: ./docker
    volumes:
      - .:/usr/share/nginx/html/
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html/
    ports:
      - "80:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"